services:
  backend:
    build:
      context: ./backend
      dockerfile: ../infra/Dockerfile.backend
    ports:
      - "5000:3001"
    environment:
      # DATABASE_URL deve ser injetada pelo Easypanel/Ambiente para o Supabase
      PORT: 3001
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
