FROM node:18-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3001

# O comando dev agora inclui npx prisma generate e db push
CMD ["npm", "run", "dev"]
